### ISSUE TITLE
sbt spark/assembly fails

### ISSUE THREAD

**Issue by josephwinston** [velvia/FiloDB#10]
I'm trying to follow the directions in Using Spark to ingest and query data.

When I run  `sbt spark/assembly`, on `OS X 10.10.5`, `Java 1.8.0_60`, and `sbt  0.13.7`, using commit `e90b7, `sbt spark/assembly` reports:

```bash
...
[info] SaveAsFiloTest:
[info] Exception encountered when attempting to run a suite with class name: filodb.spark.SaveAsFiloTest *** ABORTED ***
[info]   com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.TransportException: [localhost/127.0.0.1:9042] Cannot connect))
[info]   at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:223)
[info]   at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:78)
[info]   at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1230)
[info]   at com.datastax.driver.core.Cluster.init(Cluster.java:157)
[info]   at com.datastax.driver.core.Cluster.connect(Cluster.java:245)
[info]   at com.websudos.phantom.connectors.DefaultCassandraManager$$anonfun$initIfNotInited$1.apply(DefaultCassandraManager.scala:113)
[info]   at com.websudos.phantom.connectors.DefaultCassandraManager$$anonfun$initIfNotInited$1.apply(DefaultCassandraManager.scala:112)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.package$.blocking(package.scala:50)
[info]   at com.websudos.phantom.connectors.DefaultCassandraManager.initIfNotInited(DefaultCassandraManager.scala:112)
[info]   ...
[info] ScalaTest
[info] Run completed in 4 seconds, 343 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error: Total 1, Failed 0, Errors 1, Passed 0
[error] Error during tests:
[error] 	filodb.spark.SaveAsFiloTest
[error] (spark/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Aug 31, 2015 6:35:36 PM
```

**Comment by josephwinston** [comment]
User error.  Before running `sbt spark/assembly`, start cassandra. Please add this to the documentation for us neophytes.

**Comment by velvia** [comment]
Updated README

**Comment by josephwinston** [comment]
Thank your
